os: linux
dist: bionic

language: node_js
node_js: 12
cache: npm

script:
  - npm run build
  - npm run lint
  - npm run test

deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL_ADDRESS
  api_token: $NPM_AUTH_TOKEN
  on:
    branch: main
    tags: true
